services:
  - type: web
    name: fantasy-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: "https://tu-frontend.vercel.app"
      - key: COOKIE_SECURE
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: fantasy-db
          property: connectionString

databases:
  - name: fantasy-db
    plan: free
    databaseName: fantasy_db
    user: fantasy_user