# Generated by Django 5.2.7 on 2025-10-04 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('DEL', 'Delantero')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_totales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('presupuesto_inicial', models.DecimalField(decimal_places=2, default=50000000, max_digits=10)),
                ('jornada_actual', models.IntegerField(default=1)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.liga')),
            ],
            options={
                'unique_together': {('liga', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, to='fantasy.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.liga')),
            ],
            options={
                'unique_together': {('usuario', 'liga')},
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.jornada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'jornada')},
            },
        ),
    ]
