# Generated by Django 5.2.7 on 2025-10-16 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('jornada_actual', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.IntegerField(default=150000000)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('DEL', 'Delantero')], max_length=3)),
                ('valor', models.IntegerField(default=5000000)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('en_venta', models.BooleanField(default=False)),
                ('en_banquillo', models.BooleanField(default=True)),
                ('fecha_mercado', models.DateTimeField(blank=True, null=True)),
                ('fecha_fichaje', models.DateTimeField(blank=True, null=True)),
                ('precio_venta', models.IntegerField(blank=True, null=True)),
                ('puja_actual', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='fantasy.equipo')),
                ('equipo_pujador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pujas_actuales', to='fantasy.equipo')),
                ('equipo_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.equiporeal')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=10)),
                ('categoria', models.CharField(choices=[('distribucion_dinero', 'Distribución de Dinero'), ('traspaso', 'Traspaso'), ('oferta_rechazada', 'Oferta Rechazada')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('equipo_ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to='fantasy.equipo')),
                ('equipo_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='fantasy.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='fantasy.jugador')),
            ],
            options={
                'ordering': ['-fecha_oferta'],
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_puja', models.DateTimeField(auto_now_add=True)),
                ('es_ganadora', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_retirada', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='fantasy.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='fantasy.jugador')),
            ],
            options={
                'ordering': ['-monto', 'fecha_puja'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='fantasy.equiporeal')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='fantasy.equiporeal')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='fantasy.jornada')),
            ],
            options={
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['jornada', 'fecha'], name='fantasy_par_jornada_54c9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.jornada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'jornada')},
            },
        ),
    ]
