# Generated by Django 5.2.7 on 2025-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('distribucion_dinero', 'Distribución de Dinero'), ('traspaso', 'Traspaso'), ('oferta_rechazada', 'Oferta Rechazada'), ('oferta_editada', 'Oferta Editada'), ('oferta_retirada', 'Oferta Retirada')], max_length=20),
        ),
    ]
