# Generated by Django 5.2.7 on 2025-10-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='en_banquillo',
            field=models.BooleanField(default=True),
        ),
    ]
