# Generated by Django 5.2.7 on 2025-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_jugador_goles_alter_notificacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntuacion',
            name='goles',
            field=models.IntegerField(default=0),
        ),
    ]
