# Generated by Django 5.2.7 on 2025-10-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_jugador_en_banquillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_fichados', to='fantasy.equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(related_name='equipos_mtm', to='fantasy.jugador'),
        ),
    ]
