# Generated by Django 5.2.7 on 2025-10-07 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_jugador_equipo_alter_equipo_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='duracion_mercado',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_mercado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
