# Generated by Django 5.2.7 on 2025-10-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_puntuacion_goles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='alineaciones_congeladas',
            field=models.BooleanField(default=False, help_text='Indica si las alineaciones ya fueron registradas para esta jornada'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio de la jornada. Las alineaciones se congelan en este momento.', null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='es_del_sistema',
            field=models.BooleanField(default=False, help_text='True si es una oferta automática generada por el sistema'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('distribucion_dinero', 'Distribución de Dinero'), ('traspaso', 'Traspaso'), ('oferta_rechazada', 'Oferta Rechazada'), ('oferta_editada', 'Oferta Editada'), ('oferta_retirada', 'Oferta Retirada'), ('puja_ganada', 'Puja Ganada'), ('puja_perdida', 'Puja Perdida'), ('puja_superada', 'Puja Superada'), ('oferta_sistema', 'Oferta del Sistema'), ('fichaje_global', 'Fichaje Global'), ('dinero_jornada', 'Dinero de Jornada'), ('sin_dinero_jornada', 'Sin Dinero en Jornada'), ('posicion_vacia', 'Posición Vacía'), ('alineacion_congelada', 'Alineación Congelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='equipo_ofertante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_realizadas', to='fantasy.equipo'),
        ),
        migrations.CreateModel(
            name='AlineacionCongelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_congelacion', models.DateTimeField(auto_now_add=True)),
                ('tiene_posiciones_completas', models.BooleanField(default=True, help_text='False si le falta alguna posición requerida (1 POR, 2 DEF, 2 DEL)')),
                ('posiciones_faltantes', models.JSONField(blank=True, default=list, help_text="Lista de posiciones que faltan: ['POR', 'DEF', 'DEL']")),
                ('puntos_obtenidos', models.IntegerField(default=0, help_text='Puntos acumulados por los titulares en esta jornada')),
                ('dinero_ganado', models.IntegerField(default=0, help_text='Dinero ganado en esta jornada (puntos × 100.000€)')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_congeladas', to='fantasy.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_alineacion', to='fantasy.jornada')),
                ('jugadores_titulares', models.ManyToManyField(related_name='alineaciones_congeladas_titular', to='fantasy.jugador')),
            ],
            options={
                'verbose_name': 'Alineación Congelada',
                'verbose_name_plural': 'Alineaciones Congeladas',
                'ordering': ['jornada__numero', 'equipo__nombre'],
                'unique_together': {('equipo', 'jornada')},
            },
        ),
    ]
