# Generated by Django 5.2.7 on 2025-10-21 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_jornada_alineaciones_congeladas_jornada_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='alineaciones_congeladas',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='es_del_sistema',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('distribucion_dinero', 'Distribución de Dinero'), ('traspaso', 'Traspaso'), ('oferta_rechazada', 'Oferta Rechazada'), ('oferta_editada', 'Oferta Editada'), ('oferta_retirada', 'Oferta Retirada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='equipo_receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_recibidas', to='fantasy.equipo'),
        ),
    ]
