# Generated by Django 5.2.7 on 2025-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_jugador_duracion_mercado_jugador_fecha_mercado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='duracion_mercado',
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_fichaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
