# Generated by Django 5.2.7 on 2025-10-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_remove_jugador_duracion_mercado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='presupuesto',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='valor',
            field=models.IntegerField(default=5000000),
        ),
    ]
