# Generated by Django 5.2.7 on 2025-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_alter_equipo_presupuesto_alter_jugador_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='presupuesto',
            field=models.IntegerField(default=150000000),
        ),
    ]
