# Generated by Django 5.2.7 on 2025-10-07 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_alter_equipo_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='fantasy.equipo'),
        ),
    ]
