# Generated by Django 5.2.7 on 2025-10-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0008_remove_equipo_jugadores_alter_jugador_equipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="precio_venta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jugador",
            name="puja_actual",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("retirada", "Retirada"),
                            ("expirada", "Expirada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_oferta", models.DateTimeField(auto_now_add=True)),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                (
                    "equipo_ofertante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas_realizadas",
                        to="fantasy.equipo",
                    ),
                ),
                (
                    "equipo_receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas_recibidas",
                        to="fantasy.equipo",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="fantasy.jugador",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_oferta"],
            },
        ),
        migrations.CreateModel(
            name="Puja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.IntegerField()),
                ("fecha_puja", models.DateTimeField(auto_now_add=True)),
                ("es_ganadora", models.BooleanField(default=False)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pujas",
                        to="fantasy.equipo",
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pujas",
                        to="fantasy.jugador",
                    ),
                ),
            ],
            options={
                "ordering": ["-monto", "fecha_puja"],
            },
        ),
    ]
