# Generated by Django 5.2.7 on 2025-10-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_jugador_equipo_pujador_jugador_precio_venta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alineacion',
        ),
    ]
