# Generated by Django 5.2.7 on 2025-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_tiponotificacion_notificacion_transaccioneconomica'),
    ]

    operations = [
        migrations.AddField(
            model_name='puja',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puja',
            name='fecha_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
